name: Release

on:
  push:
    branches:
      - master
      - next

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup git user 
        uses: fregante/setup-git-user@v1

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '23'

      - name: Install dependencies
        run: yarn install

      - name: Test
        run: yarn test

      - name: Build
        run: yarn build

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn semantic-release
      
      - name: Publish to npm
        run: |
            CURRENT_VERSION=$(npm show pdjenera-component-library version)
            LOCAL_VERSION=$(node -pe "require('./package.json').version")

            if [ "$CURRENT_VERSION" != "$LOCAL_VERSION" ]; then
              echo "Versions are different. Publishing to npm."
              echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
              yarn publish
            else
              echo "Versions are the same. Skipping npm publish."
            fi 
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}