on:
  push:
   branches:
     - master

jobs:
  generate_release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        
      - name: Fetch version
        run: |
          VERSION=$(echo "${GITHUB_HEAD_REF}" | sed "s/release\\/v//")
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
        id: fetch-version
        
      - name: Generate release notes
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: v${{ steps.fetch-version.outputs.version }}
          generate_release_notes: true
